version: "3.8"

services:
  test-app:
    container_name: test-app-container
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev
